import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import HeaderPage from "./components/Header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"], // You can add more weights if needed
  variable: "--font-roboto", // Optional: for CSS variable usage
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} min-h-screen bg-white dark:bg-gray-900 transition-colors duration-200`}
      >
        <div className="container mx-auto p-4">
          <HeaderPage />
          {children}
        </div>
      </body>
    </html>
  );
}
